global:
  resolve_timeout: 1m
  slack_api_url: ''
templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  receiver: 'slack'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        title: '{{ template "slack.custom.title" . }}'
        text: '{{ template "slack.custom.text" . }}'
        username: 'Prometheus'
